### ISSUE TITLE
本地不能运行啊

### ISSUE THREAD

**Issue by sizj97** [bighammer-link/NeteaseMusci_Upgrade#1]
PS E:\docker\NeteaseMusic_Upgrade-main> python.exe .\main.py
Traceback (most recent call last):
  File "E:\docker\NeteaseMusic_Upgrade-main\main.py", line 191, in <module>
    main()
  File "E:\docker\NeteaseMusic_Upgrade-main\main.py", line 179, in main
    user_cookies, user_uid = code_login()
                             ^^^^^^^^^^^^
  File "E:\docker\NeteaseMusic_Upgrade-main\main.py", line 55, in code_login
    img.save('code.jpg')
  File "D:\Python\Python311\Lib\site-packages\qrcode\image\pure.py", line 26, in save
    self._img.write(stream, self.rows_iter())
  File "D:\Python\Python311\Lib\site-packages\png.py", line 668, in write
    nrows = self.write_passes(outfile, check_rows(rows))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\png.py", line 703, in write_passes
    return self.write_packed(outfile, rows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\png.py", line 723, in write_packed
    self.write_preamble(outfile)
  File "D:\Python\Python311\Lib\site-packages\png.py", line 771, in write_preamble
    outfile.write(signature)
    ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'write'

**Comment by bighammer-link** [comment]
可能是你的依赖的问题，你更新一下依赖试试
